# users.py

users = [
    {
        "id": 1,
        "name": "Dr. Rajesh Kumar",
        "role": "doctor",
        "active_shift": True,
        "team": "emergency",
    },
    {
        "id": 2,
        "name": "Nurse Priya Sharma",
        "role": "nurse",
        "active_shift": True,
        "team": "emergency",
    },
    {
        "id": 3,
        "name": "Admin Suresh Verma",
        "role": "admin",
        "active_shift": False,
        "team": "admin",
    },
    {
        "id": 4,
        "name": "Ambulance Rani Gupta",
        "role": "ambulance",
        "active_shift": True,
        "team": "emergency",
    },
    {
        "id": 5,
        "name": "Pharmacist Meena Desai",
        "role": "pharmacist",
        "active_shift": True,
        "team": "pharmacy",
    },
    {
        "id": 6,
        "name": "Receptionist Nisha Patel",
        "role": "receptionist",
        "active_shift": True,
        "team": "admin",
    },
    {
        "id": 7,
        "name": "Lab Tech Vinod Bansal",
        "role": "lab_technician",
        "active_shift": True,
        "team": "lab",
    },
    {
        "id": 8,
        "name": "Billing Clerk Aarti Yadav",
        "role": "billing_clerk",
        "active_shift": True,
        "team": "billing",
    },
    {
        "id": 9,
        "name": "Surgeon Kavita Mehta",
        "role": "surgeon",
        "active_shift": True,
        "team": "surgery",
    },
    {
        "id": 10,
        "name": "Anesthesiologist Ravi Reddy",
        "role": "anesthesiologist",
        "active_shift": True,
        "team": "surgery",
    },
    {
        "id": 11,
        "name": "Physician Seema Iyer",
        "role": "physician",
        "active_shift": True,
        "team": "emergency",
    },
    {
        "id": 12,
        "name": "X-Ray Tech Kiran Chopra",
        "role": "xray_technician",
        "active_shift": True,
        "team": "radiology",
    },
    {
        "id": 13,
        "name": "Dr. Arun Soni",
        "role": "doctor",
        "active_shift": True,
        "team": "emergency",
    },
    {
        "id": 14,
        "name": "Nurse Geeta Khanna",
        "role": "nurse",
        "active_shift": True,
        "team": "emergency",
    },
    {
        "id": 15,
        "name": "Admin Shweta Rani",
        "role": "admin",
        "active_shift": False,
        "team": "admin",
    },
    {
        "id": 16,
        "name": "Ambulance Sunita Desai",
        "role": "ambulance",
        "active_shift": True,
        "team": "emergency",
    },
    {
        "id": 17,
        "name": "Pharmacist Deepak Singh",
        "role": "pharmacist",
        "active_shift": True,
        "team": "pharmacy",
    },
    {
        "id": 18,
        "name": "Receptionist Pooja Bhatia",
        "role": "receptionist",
        "active_shift": True,
        "team": "admin",
    },
    {
        "id": 19,
        "name": "Lab Tech Radha Verma",
        "role": "lab_technician",
        "active_shift": True,
        "team": "lab",
    },
    {
        "id": 20,
        "name": "Billing Clerk Nisha Patel",
        "role": "billing_clerk",
        "active_shift": True,
        "team": "billing",
    },
    {
        "id": 21,
        "name": "Surgeon Sanjay Kumar",
        "role": "surgeon",
        "active_shift": True,
        "team": "surgery",
    },
    {
        "id": 22,
        "name": "Anesthesiologist Neha Gupta",
        "role": "anesthesiologist",
        "active_shift": True,
        "team": "surgery",
    },
    {
        "id": 23,
        "name": "Physician Amit Yadav",
        "role": "physician",
        "active_shift": True,
        "team": "emergency",
    },
    {
        "id": 24,
        "name": "X-Ray Tech Shweta Bansal",
        "role": "xray_technician",
        "active_shift": True,
        "team": "radiology",
    },
    {
        "id": 25,
        "name": "Dr. Kiran Khanna",
        "role": "doctor",
        "active_shift": True,
        "team": "emergency",
    },
    {
        "id": 26,
        "name": "Nurse Sushma Sharma",
        "role": "nurse",
        "active_shift": True,
        "team": "emergency",
    },
    {
        "id": 27,
        "name": "Admin Priya Mehta",
        "role": "admin",
        "active_shift": False,
        "team": "admin",
    },
    {
        "id": 28,
        "name": "Ambulance Vinod Reddy",
        "role": "ambulance",
        "active_shift": True,
        "team": "emergency",
    },
    {
        "id": 29,
        "name": "Pharmacist Aarti Singh",
        "role": "pharmacist",
        "active_shift": True,
        "team": "pharmacy",
    },
    {
        "id": 30,
        "name": "Receptionist Radha Patel",
        "role": "receptionist",
        "active_shift": True,
        "team": "admin",
    },
    {
        "id": 31,
        "name": "Lab Tech Asha Yadav",
        "role": "lab_technician",
        "active_shift": True,
        "team": "lab",
    },
    {
        "id": 32,
        "name": "Billing Clerk Seema Iyer",
        "role": "billing_clerk",
        "active_shift": True,
        "team": "billing",
    },
    {
        "id": 33,
        "name": "Surgeon Rajesh Gupta",
        "role": "surgeon",
        "active_shift": True,
        "team": "surgery",
    },
    {
        "id": 34,
        "name": "Anesthesiologist Ramesh Bansal",
        "role": "anesthesiologist",
        "active_shift": True,
        "team": "surgery",
    },
    {
        "id": 35,
        "name": "Physician Vinod Rani",
        "role": "physician",
        "active_shift": True,
        "team": "emergency",
    },
]
